
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.1'
        -
            os: 'osx'
            language: 'generic'
            env:
                - >-
                    BREW_PHP=php71

before_install:
    - 'src-dev/scripts/travis/before_install.sh'
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'
    - "export CUSTOM_RUBY_VERSION=$(BUNDLE_GEMFILE='tests/_data/Gemfile.fail.rb' bundle platform --ruby | awk '{print $2}')"
    - 'echo "The expected ruby version is ${CUSTOM_RUBY_VERSION}"'
    - 'rvm install "${CUSTOM_RUBY_VERSION}"'
    - 'rvm --default use "${CUSTOM_RUBY_VERSION}"'
    - 'ruby --version'
    - 'gem install bundler'
    - 'BUNDLE_GEMFILE=tests/_data/Gemfile.success.rb bundle install'

install:
    - 'composer install'

script:
    - './bin/robo --ansi lint'
    - './bin/robo --ansi test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
