
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.1'
# Drop OSX support because of the mysterious
# TTY mode requires /dev/tty to be read/writable.
# error.
#        -
#            os: 'osx'
#            language: 'generic'

before_install:
    - 'src-dev/scripts/travis/before_install.sh'
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'
    - "export CUSTOM_RUBY_VERSION=$(BUNDLE_GEMFILE='tests/_data/Gemfile.fail.rb' bundle platform --ruby | awk '{print $2}')"
    - 'export BREW_PHP=php71'
    - 'rvm install "${CUSTOM_RUBY_VERSION}"'
    - 'rvm --default use "${CUSTOM_RUBY_VERSION}"'
    - 'ruby --version'

install:
    - 'composer install --no-progress'

script:
    - 'bin/robo lint'
    - 'bin/robo test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
